### ISSUE TITLE
Integrated Shrinking

### ISSUE THREAD

**Issue by cstorey** [rust-fuzz/rust_arbitrary#2]
In short, Hypothesis provides [integrated shrinking](https://hypothesis.works/articles/integrated-shrinking/) without needing to implement a separate shrinker per type by shrinking the fuzzed byte input, rather than the generated value.

I've got an implementation of this in my [suppositions](http://docs.rs/suppositions) crate, and I'm sure there's something similar in [proptest](http://docs.rs/proptest) too.

**Comment by nagisa** [comment]
Fair point, but shrinking is mostly not a focus for the library currently (the fuzzer up above deals with it and they shrink the byte array from which the data is generated).

I would love to work on making this library more complete, but now that fuzzing in Rust is goodenough™, my interest has waned somewhat, and I’d rather allocate the little amount of time I have to other things :)

**Comment by fitzgen** [comment]
We have shrinking overrides for `Arbitrary` impls filled out now, so I think we can close this issue, between that and libfuzzer's shrinking support.
