### ISSUE TITLE
Arbitrary impl for char is slow

### ISSUE THREAD

**Issue by Manishearth** [rust-fuzz/rust_arbitrary#8]
The current implementation, when it hits an invalid character, loops downward by one bit each time. This is slow, all of the invalid `char` values are between `0xD800` and  `0xDFFF`, or greater than `0x10ffff` (already dealt with with the mask)

This means that we spend a lot of time just looping here, especially when creating strings. We should instead just replace these with null or decrement the fourth nibble.

**Comment by Manishearth** [comment]
Also, we might want to try directly constructing strings? In the past I've had good luck with just `String::from_utf8` on byte slices whilst fuzzing. It's fast and it has found many bugs. The current `String` implementation seems unable to find things even in cases where the testcase is literally "panic on this particular six-character string"

**Comment by Manishearth** [comment]
Sadly the current design of the `Arbitrary` trait leaves no room for "try to construct a string, error out if it fails" :/

**Comment by fitzgen** [comment]
> Sadly the current design of the `Arbitrary` trait leaves no room for "try to construct a string, error out if it fails" :/

I guess you could do a lossy utf8 conversion, but that might not always be appropriate.

**Comment by nagisa** [comment]
Very open to larger changes to the trait, including adding potential error branches, but I personally think that people do not want to care about these details and would rather just get something.

Especially relevant if and when rngs get involved behind this trait.

Might be worth looking at how `quickcheck` has implemented generation of `char`.

**Comment by Manishearth** [comment]
quickcheck is able to request infinite bytes, we cannot. It uses the `rand` crate's way of requesting chars with standard distribution (https://docs.rs/rand/0.7.2/src/rand/distributions/other.rs.html#42-61) but that does mean the input bytestring will not look at all like the output because it will be shifted, which isn't great for fuzzers -- fuzzers like to look at programs and generate things containing strings found in the program.

>  I personally think that users of this trait do not want to care about these details and would rather just get something.

The main user of this trait is the fuzzer stuff, and in fuzzing it makes more sense to reject early than to spend lots of effort trying to come up with a valid value.

**Comment by Manishearth** [comment]
I'm not strong on having the reject-early stuff, but we should definitely fix it so that in the case where the fuzzer gives us an invalid byte we don't put lots of effort into "fixing" it

**Comment by nagisa** [comment]
change the impl to be `for Option<char>` instead, maybe?

**Comment by Manishearth** [comment]
Perhaps. We should fix the perf issue first, and then look at the API if
necessary

**Comment by Manishearth** [comment]
We should reuse the existing logic that libFuzzer has for all this: https://github.com/rust-fuzz/libfuzzer-sys/blob/master/libfuzzer/utils/FuzzedDataProvider.h

**Comment by nagisa** [comment]
> We should reuse the existing logic that libFuzzer has for all this: https://github.com/rust-fuzz/libfuzzer-sys/blob/master/libfuzzer/utils/FuzzedDataProvider.h

Interesting, but that should go directly into libfuzzer IMO. Adding some more user-visible support likely warrants nicer wrapper than what we have currently in libfuzzer crate too.

**Comment by Manishearth** [comment]
You misunderstand, I'm not suggesting we use that code, I'm suggesting we
copy the byte extraction techniques

**Comment by fitzgen** [comment]
> We should reuse the existing logic that libFuzzer has for all this: https://github.com/rust-fuzz/libfuzzer-sys/blob/master/libfuzzer/utils/FuzzedDataProvider.h

I don't see anything in here about unicode or utf-8 -- am I missing something?

**Comment by fitzgen** [comment]
Is this a good enough implementation for this method

```rust
let c = u32::arbitrary(u)?;
Ok(u32::try_from(c).unwrap_or(char::REPLACEMENT_CHARACTER))
```

?

**Comment by Manishearth** [comment]
> I don't see anything in here about unicode or utf-8 -- am I missing something?

ConsumeIntegralInRange has the kind of stuff I was thinking of.

> Is this a good enough implementation for this method

No, the point is to _only_ generate valid characters, not try to generate characters and fail with a replacement. If we do that then the fuzzer will be heavily biased towards the replacement character.

-------

I was going to suggest we do something similar to https://docs.rs/rand/0.7.2/src/rand/distributions/other.rs.html#42-61  , but I have a better idea.

Valid `char`s are in `[0, 0xD800)` plus `(0xDFFF, 0x11_0000)` (as seen in the rand source).  This is essentially `[0, 0x11_0000)` with a gap for the surrogates in `[0xD800, 0xDFFF)`.

What we can do is generate an integer, modulus it by `0x11_0000`, and if it happens to be in the range `[0xD800, 0xDFFF)` (this is the only time `char::try_from` will fail), then subtract `0xDFFF - 0xD800 + 1` and try again.

This is really nice because it's not _super_ biased (it's a little bit biased towards the blocks that come immediately before the surrogates, but we can't do much about that), and also it preserves input bytes as much as possible, which means that libfuzzer's ability to "guess" strings based on program static data is useful.


(It occurs to me that at this point I've already figured out the implementation and might as well write it. Maybe tomorrow)

**Comment by Manishearth** [comment]
ugh it's trickier than that, the char impl is fixable but the string impl should not use the char impl since the char impl is utf 32

**Comment by Manishearth** [comment]
https://github.com/rust-fuzz/rust_arbitrary/pull/16
